### ISSUE TITLE
Potential count inconsistency

### ISSUE THREAD

**Issue by omar-scio** [tiktoken-go/tokenizer#2]
I'm using this repo mainly to count the tokens. I have one feature request and one issue. I'll start with the issue:

Should I expect the same output from this library and https://platform.openai.com/tokenizer? I'm seeing different numbers and tokens. If yes, for which models?

The feature request is to have a `GetTokensCount` function. It'd also be helpful if the existing functions had annotations so I can better understand what they do, particularly around the return values. Things like `([]uint, []string, error)` aren't super helpful since I'm not sure what the semantic meaning of these return values are without reading the code.

**Comment by bluescreen10** [comment]
Thanks for the feedback. I'll see how to add documentstion for the return types.

Let me address your questions.
1) there are different types of encodings supported by tiktoen and I believe the website is not using their latest encoding "cl100k_base" try with "p50k_base" and see if you get the same count and ids. If not please report a bug.

2) to count tokens is really simple, the encode method returns a list of token ids, the tokens and an error. Either `len(tokenIDs)` or `len(tokens)` (the first two elements of the response) would achieve what you are looking for. The reason both are returned is because sometimes is useful to have the tokens so if you need to split the text you don't need to decode ids.

Hope this helps. 🙌

**Comment by omar-scio** [comment]
Thanks @bluescreen10! That makes sense, using `p50k_base` made the numbers match up as expected. Sounds like we'll keep the code the same (i.e. not using `p50k_base`) since it seems that it's the website that is out of date.

Appreciate the answer :)
