### ISSUE TITLE
Incorrect calculation for Chinese characters

### ISSUE THREAD

**Issue by hyp530** [tiktoken-go/tokenizer#5]
The number of tokens deviates a lot comparing to https://platform.openai.com/tokenizer.

**Comment by ghost** [comment]
Hi, thanks for reporting this, can you provide a concrete example?

**Comment by hyp530** [comment]
The number of tokens deviates a lot comparing to https://platform.openai.com/tokenizer.

package main

import (
	"fmt"
	"github.com/pkoukk/tiktoken-go"
)

func main() {
	text := "这是一个测试"
	tke, _ := tiktoken.GetEncoding("cl100k_base")
	token := tke.Encode(text, nil, nil)
	fmt.Println(len(token)) // Result:  4
}
The result is 10 as generated by [OpenAI Tokenizer](https://platform.openai.com/tokenizer) .

**Comment by bluescreen10** [comment]
Hi, I was able to compare against [OpenAI/tiktoken](https://github.com/openai/tiktoken) with the following code and I'm also getting 4 tokens back. I believe in their website they use `p50k_base` (not `cl100k_base`) so that's the difference you are observing. Try using the other model I've mentioned and see if you get 10 tokens back.

Code:
```python
import tiktoken
enc = tiktoken.get_encoding("cl100k_base")
enc.encode("这是一个测试")
```

Output:
```
[44388, 21043, 48044, 82805]
```
